<?php /** @var Clearpay_Clearpay_Block_Banner $this */ ?>
<script type="text/javascript">
    document.observe('dom:loaded', function () {
        var bannerConfig = <?php echo json_encode($this->getJsConfig()) ?>,
            bannerAfterBlock = Prototype.Selector.select(bannerConfig.selector, document),
            bannerClassName = bannerConfig.className;

        try {
            var bannerBlocks = $$('.' + bannerClassName);
            if (bannerAfterBlock[0] && bannerBlocks[0]) {
                bannerAfterBlock[0].insert({after: bannerBlocks[0]});
            }
        } catch (e) {
            window.console && console.log('Clearpay: Error on processing banner block element: ', e);
        }
    });
</script>
