<div id="clearpay-what-is-modal" style="display:none;">
    <a href="https://www.clearpay.co.uk/terms/" target="_blank" style="border: none">
        <img class="clearpay-modal-image" src="https://static.afterpay.com/clearpay-lightbox-desktop.png" alt="Clearpay" />
        <img class="clearpay-modal-image-mobile" src="https://static.afterpay.com/clearpay-lightbox-mobile.png" alt="Clearpay" />
    </a>
</div>