<?php /** @var $this Clearpay_Clearpay_Block_Form_Payovertime */ ?>
<div id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div id="<?php echo $this->getDetailsTemplateId() ?>"></div>
</div>

<script type="text/javascript">

    /** @require /js/Clearpay/checkout/payovertime.js */
    Clearpay.CheckoutForm.detailsConfiguration = <?php echo json_encode($this->getDetailsConfiguration()) ?>;

//    // render pay over time checkout option form on dom:loaded event
//    document.observe('dom:loaded', function () {
//    });
    Clearpay.CheckoutForm.detailsRender();

    jQuery(Clearpay.CheckoutForm.detailsConfiguration.creditUsedSelector).on('change', function(){
        Clearpay.CheckoutForm.detailsRender();
    });

</script>
