<?php if (Mage::helper('clearpay/checkout')->noConflict()) { ?>
<script src="<?php echo Mage::getBaseUrl('js') . 'Clearpay/checkout/payovertime.js'; ?>"></script>
<script>
//<![CDATA[
    window.Clearpay = window.Clearpay || {};
    window.Clearpay.redirectMode = "<?php echo $this->getMode() ?>";
    window.Clearpay.saveUrl = "<?php echo $this->getUrl('clearpay/payment/start', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>";
//]]>
</script>
<?php } ?>
