<?php
$region_specific_text = 'fortnightly';
?>
<span class="paypal-or"><?php echo $this->__('-OR-'); ?></span>
</li><li class="method-clearpay_onetouch">

<h3><?php echo $this->__('Check out with Clearpay and pay over time.') ?></h3>
<p><?php echo $this->__('Simply pay 4 ' . $region_specific_text . ' payments of %s.', $this->getInstalmentAmount()) ?></p>
<p>
    <?php echo $this->__('Use your payment card, instant approval.') ?>
    <a href="#clearpay-what-is-modal" class="clearpay-what-is-modal-trigger">
        <?php echo $this->__('Learn more') ?>
    </a>
</p>
<a href="<?php echo $this->getUrl('clearpay/onetouch') ?>" class="button btn-proceed-checkout btn-checkout">
    <img src="https://static.afterpay.com/integration/logo-clearpay-white-162x31.png" />
</a>
