<img src="<?php echo $this->getSkinUrl('clearpay/images/clearpay-logo-163x31.png') ?>" class="v-middle" id="clearpay-logo" />
<span id="clearpay-callout"><?php echo $this->__('Pay four interest-free payments every 2 weeks.') ?></span>
<a href="#clearpay-what-is-modal" id="what-is-clearpay-trigger">
    <?php echo $this->__('What is Clearpay?') ?>
</a>
<script>
    //<![CDATA[
    // included inline as this template is loaded through an ajax request
    jQuery('#what-is-clearpay-trigger').fancybox({
        afterShow: function() {
            jQuery('#clearpay-what-is-modal').find('.close-clearpay-button').on('click', function(event) {
                event.preventDefault();
                jQuery.fancybox.close();
            })
        }
    });
    //]]>
</script>
